Repository LikeMindsCommunity/likeminds-chat-reactnative, pull requests merged in 2024-08, with the labels that each got.

#56 [LM-12505] Last conversation showing voice note fix
  example/src/enums/screenNameEnums.ts
  likeminds-chat-reactnative-integration/ChatSX/components/HomeFeedItem/index.tsx
  likeminds-chat-reactnative-integration/ChatSX/components/InputBox/index.tsx
  likeminds-chat-reactnative-integration/ChatSX/components/MessageList/index.tsx
Labels: bug

#55 [LM-12229] Migration: Target SDK 34
  example/App.tsx
  example/android/build.gradle
  example/ios/example.xcodeproj/project.pbxproj
  example/ios/example.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  example/ios/example/PrivacyInfo.xcprivacy
  example/package-lock.json
  example/package.json
  example/screens/Chatroom/ChatroomScreen.tsx
  example/src/enums/screenNameEnums.ts
  likeminds-chat-reactnative-integration/ChatSX/components/InputBox/index.tsx
Labels: enhancement

#57 [LM-12380] chat stability bugs
  likeminds-chat-reactnative-integration/ChatSX/components/InputBox/index.tsx
  likeminds-chat-reactnative-integration/ChatSX/components/MessageList/index.tsx
  likeminds-chat-reactnative-integration/ChatSX/context/ChatroomContext.tsx
  likeminds-chat-reactnative-integration/ChatSX/screens/ChatRoom/index.tsx
  likeminds-chat-reactnative-integration/ChatSX/screens/HomeFeed/Tabs/DMFeed/index.tsx
  likeminds-chat-reactnative-integration/ChatSX/store/reducers/chatroomReducer.ts
Labels: bug

#58 [v1.2.0] Version Upgrade
  cbc/package.json
  example/package.json
  likeminds-chat-reactnative-integration/ChatSX/setup.ts
  likeminds-chat-reactnative-integration/package.json
Labels: enhancement

#59 Release/v1.2.0
  cbc/package.json
  example/App.tsx
  example/android/build.gradle
  example/ios/example.xcodeproj/project.pbxproj
  example/ios/example.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  example/ios/example/PrivacyInfo.xcprivacy
  example/package-lock.json
  example/package.json
  example/screens/Chatroom/ChatroomScreen.tsx
  example/src/enums/screenNameEnums.ts
  likeminds-chat-reactnative-integration/ChatSX/components/HomeFeedItem/index.tsx
  likeminds-chat-reactnative-integration/ChatSX/components/InputBox/index.tsx
  likeminds-chat-reactnative-integration/ChatSX/components/MessageList/index.tsx
  likeminds-chat-reactnative-integration/ChatSX/context/ChatroomContext.tsx
  likeminds-chat-reactnative-integration/ChatSX/screens/ChatRoom/index.tsx
  likeminds-chat-reactnative-integration/ChatSX/screens/HomeFeed/Tabs/DMFeed/index.tsx
  likeminds-chat-reactnative-integration/ChatSX/setup.ts
  likeminds-chat-reactnative-integration/ChatSX/store/reducers/chatroomReducer.ts
  likeminds-chat-reactnative-integration/package.json
Labels: release

#61 [LM-12639] Chat Bugs
  likeminds-chat-reactnative-integration/ChatSX/components/CommonAllMembers/index.tsx
  likeminds-chat-reactnative-integration/ChatSX/components/DeletedMessage/index.tsx
  likeminds-chat-reactnative-integration/ChatSX/components/ExploreFeedItem/styles.ts
  likeminds-chat-reactnative-integration/ChatSX/components/HomeFeedItem/styles.ts
  likeminds-chat-reactnative-integration/ChatSX/components/LinkPreview/index.tsx
  likeminds-chat-reactnative-integration/ChatSX/components/LinkPreview/styles.ts
  likeminds-chat-reactnative-integration/ChatSX/components/MessageList/index.tsx
  likeminds-chat-reactnative-integration/ChatSX/components/Poll/PollConversationView/index.tsx
  likeminds-chat-reactnative-integration/ChatSX/components/ReplyConversations/index.tsx
  likeminds-chat-reactnative-integration/ChatSX/components/ReplyConversations/styles.ts
  likeminds-chat-reactnative-integration/ChatSX/components/ToastMessage/index.tsx
  likeminds-chat-reactnative-integration/ChatSX/constants/Styles.ts
  likeminds-chat-reactnative-integration/ChatSX/context/ChatroomContext.tsx
  likeminds-chat-reactnative-integration/ChatSX/context/MessageListContext.tsx
  likeminds-chat-reactnative-integration/ChatSX/screens/ChatRoom/styles.ts
Labels: bug

#60 [LM-10929] API Key Security
  example/App.tsx
  likeminds-chat-reactnative-integration/ChatSX/components/ParseDeepLink/index.ts
  likeminds-chat-reactnative-integration/ChatSX/credentials.ts
  likeminds-chat-reactnative-integration/ChatSX/lmChatProvider/index.tsx
  likeminds-chat-reactnative-integration/ChatSX/lmChatProvider/type.ts
  likeminds-chat-reactnative-integration/ChatSX/lmOverlayProvider/index.tsx
  likeminds-chat-reactnative-integration/ChatSX/lmOverlayProvider/types.ts
  likeminds-chat-reactnative-integration/ChatSX/notifications/index.ts
  likeminds-chat-reactnative-integration/ChatSX/screens/HomeFeed/index.tsx
  likeminds-chat-reactnative-integration/ChatSX/setup.ts
  likeminds-chat-reactnative-integration/ChatSX/setupChat.ts
  likeminds-chat-reactnative-integration/ChatSX/store/actions/homefeed.ts
  likeminds-chat-reactnative-integration/ChatSX/store/apiMiddleware.ts
  likeminds-chat-reactnative-integration/ChatSX/store/reducers/homefeedReducer.ts
  likeminds-chat-reactnative-integration/ChatSX/store/types/types.ts
Labels: enhancement

#62 [v.1.3.0] Version Upgrade
  example/package.json
  likeminds-chat-reactnative-integration/ChatSX/setup.ts
  likeminds-chat-reactnative-integration/package.json
Labels: enhancement

#63 Release/v1.3.0
  example/App.tsx
  example/package.json
  likeminds-chat-reactnative-integration/ChatSX/components/CommonAllMembers/index.tsx
  likeminds-chat-reactnative-integration/ChatSX/components/DeletedMessage/index.tsx
  likeminds-chat-reactnative-integration/ChatSX/components/ExploreFeedItem/styles.ts
  likeminds-chat-reactnative-integration/ChatSX/components/HomeFeedItem/styles.ts
  likeminds-chat-reactnative-integration/ChatSX/components/LinkPreview/index.tsx
  likeminds-chat-reactnative-integration/ChatSX/components/LinkPreview/styles.ts
  likeminds-chat-reactnative-integration/ChatSX/components/MessageList/index.tsx
  likeminds-chat-reactnative-integration/ChatSX/components/ParseDeepLink/index.ts
  likeminds-chat-reactnative-integration/ChatSX/components/Poll/PollConversationView/index.tsx
  likeminds-chat-reactnative-integration/ChatSX/components/ReplyConversations/index.tsx
  likeminds-chat-reactnative-integration/ChatSX/components/ReplyConversations/styles.ts
  likeminds-chat-reactnative-integration/ChatSX/components/ToastMessage/index.tsx
  likeminds-chat-reactnative-integration/ChatSX/constants/Styles.ts
  likeminds-chat-reactnative-integration/ChatSX/context/ChatroomContext.tsx
  likeminds-chat-reactnative-integration/ChatSX/context/MessageListContext.tsx
  likeminds-chat-reactnative-integration/ChatSX/credentials.ts
  likeminds-chat-reactnative-integration/ChatSX/lmChatProvider/index.tsx
  likeminds-chat-reactnative-integration/ChatSX/lmChatProvider/type.ts
  likeminds-chat-reactnative-integration/ChatSX/lmOverlayProvider/index.tsx
  likeminds-chat-reactnative-integration/ChatSX/lmOverlayProvider/types.ts
  likeminds-chat-reactnative-integration/ChatSX/notifications/index.ts
  likeminds-chat-reactnative-integration/ChatSX/screens/ChatRoom/styles.ts
  likeminds-chat-reactnative-integration/ChatSX/screens/HomeFeed/index.tsx
  likeminds-chat-reactnative-integration/ChatSX/setup.ts
  likeminds-chat-reactnative-integration/ChatSX/setupChat.ts
  likeminds-chat-reactnative-integration/ChatSX/store/actions/homefeed.ts
  likeminds-chat-reactnative-integration/ChatSX/store/apiMiddleware.ts
  likeminds-chat-reactnative-integration/ChatSX/store/reducers/homefeedReducer.ts
  likeminds-chat-reactnative-integration/ChatSX/store/types/types.ts
  likeminds-chat-reactnative-integration/package.json
Labels: release
