Repository LikeMindsCommunity/likeminds-chat-reactnative, pull requests merged in 2024-02, with the labels that each got.

#12 Product Signoff Bugs
  example/App.tsx
  example/index.js
  example/package.json
  likeminds-chat-reactnative-integration/ChatSX/components/InputBox/index.tsx
  likeminds-chat-reactnative-integration/ChatSX/components/MessageList/index.tsx
  likeminds-chat-reactnative-integration/ChatSX/components/Messages/index.tsx
  likeminds-chat-reactnative-integration/ChatSX/components/ReplyConversations/index.tsx
  likeminds-chat-reactnative-integration/ChatSX/components/Swipeable/index.tsx
  likeminds-chat-reactnative-integration/ChatSX/components/TopTabNavigator/index.tsx
  likeminds-chat-reactnative-integration/ChatSX/constants/type.ts
  likeminds-chat-reactnative-integration/ChatSX/screens/ChatRoom/index.tsx
  likeminds-chat-reactnative-integration/package.json
Labels: bug

#13 Added Readme and BackgroundImage support
  likeminds-chat-reactnative-integration/ChatSX/screens/ChatRoom/index.tsx
  likeminds-chat-reactnative-integration/README.md
  likeminds-chat-reactnative-integration/package.json
Labels: enhancement

#18 [LM-10783] Peer Dependency
  likeminds-chat-reactnative-integration/ChatSX/notifications/index.ts
  likeminds-chat-reactnative-integration/ChatSX/screens/ChatRoom/index.tsx
  likeminds-chat-reactnative-integration/ChatSX/setup.ts
  likeminds-chat-reactnative-integration/package.json
Labels: bug

#19 [LM-10817] Changes Analytics and Notifications flow
  likeminds-chat-reactnative-integration/ChatSX/analytics/LMChatAnalytics.ts
  likeminds-chat-reactnative-integration/ChatSX/commonFuctions/index.tsx
  likeminds-chat-reactnative-integration/ChatSX/commonFuctions/model.ts
  likeminds-chat-reactnative-integration/ChatSX/components/InputBox/index.tsx
  likeminds-chat-reactnative-integration/ChatSX/components/Swipeable/index.tsx
  likeminds-chat-reactnative-integration/ChatSX/constants/Strings.ts
  likeminds-chat-reactnative-integration/ChatSX/enums/MediaType.ts
  likeminds-chat-reactnative-integration/ChatSX/lmChatProvider/index.tsx
  likeminds-chat-reactnative-integration/ChatSX/navigation/SwitchComponent/index.tsx
  likeminds-chat-reactnative-integration/ChatSX/notifications/index.ts
  likeminds-chat-reactnative-integration/ChatSX/notifications/models/index.tsx
  likeminds-chat-reactnative-integration/ChatSX/screens/ChatRoom/index.tsx
  likeminds-chat-reactnative-integration/ChatSX/setup.ts
  likeminds-chat-reactnative-integration/ChatSX/utils/analyticsUtils.ts
  likeminds-chat-reactnative-integration/index.ts
  likeminds-chat-reactnative-integration/package.json
Labels: enhancement

#23 Release/v0.5.9
  example/package.json
  likeminds-chat-reactnative-integration/ChatSX/lmChatProvider/index.tsx
  likeminds-chat-reactnative-integration/package.json
Labels: enhancement

#24 [Hotfix LM-10860] Fixed Custom Back Handler
  likeminds-chat-reactnative-integration/ChatSX/callBacks/chatroomCallback.tsx
  likeminds-chat-reactnative-integration/ChatSX/components/InputBox/index.tsx
  likeminds-chat-reactnative-integration/ChatSX/constants/type.ts
  likeminds-chat-reactnative-integration/ChatSX/lmChatProvider/index.tsx
  likeminds-chat-reactnative-integration/ChatSX/screens/ChatRoom/index.tsx
  likeminds-chat-reactnative-integration/package.json
Labels: hotfix
